### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Interface'

### ISSUE THREAD

**Issue by KevinHaleydt** [NextDiffusion/next-view#2]
Hi,

did the installation as instructed here and in your video. After installation and reloading the extension is not present in the UI. (Automatic1111). Checked the cmd for errors and noticed i'm running into the following error:
AttributeError: module 'gradio' has no attribute 'Interface'

I already tried uninstalling and reinstalling the gradio module via pip install but alas. 

Any ideas how this can be resolved? 
Thanks!

**Comment by NextDiffusion** [comment]
Hi Kevin,

It seems you're encountering an issue with an outdated Gradio version. To resolve this, open your "requirements.txt" file in the root Stable Diffusion directory and ensure it includes 'gradio>=3.50.0'. Save the file, and then restart Stable Diffusion. This should enable the NextView extension to work correctly.

Greetings,
Next Diffusion.
