### ISSUE TITLE
Image2Video -  can't run if "too many images" - (WinError206 File name or extension too long)

### ISSUE THREAD

**Issue by Crezjcm** [NextDiffusion/next-view#3]
Hi, and first of all thank you for building this extension. 
I know nothing about coding but i may found "the culprit".

After testing with images in a short path (c:\a\),  the script can't complete if more than 1630 images (or less if path longer)

It seems that the crash occurs at line 86  subprocess.run(ffmpeg_cmd)

I guess ffmpeg concat becomes too long to be called by subprocess

there was no problem in previous version of the extension running+5000 image files. (besides sometimes one missing frame)

![1631](https://github.com/NextDiffusion/next-view/assets/142888383/d8e15f31-513c-4377-b53f-4f6f8f5f3ca4)
![1630](https://github.com/NextDiffusion/next-view/assets/142888383/97aed3db-9c4e-4a0d-a09c-aefb85b10d0a)

**Comment by NextDiffusion** [comment]
I conducted several tests, and indeed, an error occurred when attempting to transform a sizable batch of image sequences into a video. I reverted the code to its previous commit. Kindly "Check for updates" and "Apply and restart UI" to ensure that the encountered error has been resolved. Wishing you successful conversions! ❤️

**Comment by Crezjcm** [comment]
thank you !! it just took me...22h to figure it out and to understand and know about git reset/revert previous commit ! lol.


anyway the ffmpeg concat parameter was a very good idea to avoid possible missing one frame (for me when that happens it's either the first or last frame, purely marginal with thousands oh images), maybe it would work if you output the list of images in a temporary .text file so it will only call a file instead of the whole images string in the ffmpeg command.

thank you again, cheers !

**Comment by NextDiffusion** [comment]
Great to help! I might be diving into the code a little later tonight to
fix that issue.
The problem indeed was within the concat within the ffmpeg command.

Greetings,
Next Diffusion

**Comment by NextDiffusion** [comment]
Hi,

Quick update: we've improved our script and it can now handle missing
frames and does use a temporary file for ffmpeg.
You can check out the changes on GitHub.

Greetings,
Next Diffusion

**Comment by Crezjcm** [comment]
launched a test with 13516 images :p and it's a success !!  great job guys !

for info, at the end of process in the console,, between the purple and blue text, you'll see "frame=13516 fps=143"
i thought the generated video was bugged as i've selected 30fps in the web-ui extension, but everything is ok, that "fps" in the console point, i guess, to how many "frames" were "processed" per "second" by ffmpeg. (sorry if it was obvious for anyone)  ;)

![nv](https://github.com/NextDiffusion/next-view/assets/142888383/df949757-a068-4730-823f-8c66cbc377b1)

**Comment by Crezjcm** [comment]
hi again, may i suggest some enhancements ? i saw discussions are not opened, so i won't say more to not pollute this thread unless you authorize me. if it's a no just delete this message, i'll understand, no problem ;)
cheers !

**Comment by NextDiffusion** [comment]
Feel free to share your ideas and feature requests with us. If they align
with our future goals, we'll certainly consider them.

Greetings,
Next Diffusion

**Comment by Crezjcm** [comment]
ok thank you !
I totally agree with what you said, as those ideas are not requests, just ideas thet tend to enhance UI ergonomy.
The extension works great a flawlessly
to make it short and the more explicit possible i annoted a screenshot + one more thing that came to my mind after the +13k images generation:

- as you can see in the screenshot 3 messages above, the generation printed the same string (pts..dts...pts..dts..) all along the process, there is  nothing to follow the progression and i thought at first that it was in loop. after completition i went up in the console and saw that there was the possibility to quit with"q".   A single line with incrementing numbers during the process would be more readable.

- the picture for enhancement ideas if any could be interesting for you.
cheers!

![nv ui idea](https://github.com/NextDiffusion/next-view/assets/142888383/54181d33-87df-4652-808b-351c6853074b)

**Comment by NextDiffusion** [comment]
Appreciate your feedback! We've incorporated some UI enhancements to
enhance the user experience.
Take a look at the latest updates! These improvements wrap up for now as
I'm allocating time to other projects.
If there are still some bugs or errors of course feel free to let me know.

Greetings,
Next Diffusion
