### ISSUE TITLE
Problem running Nextview

### ISSUE THREAD

**Issue by ibarelyknowwhatimdoing** [NextDiffusion/next-view#4]
**Great tutorials, but I get an error and am having a terrible time trying find the answer.  I load a video into video 2 image sequence in Nextview tab and click generate.  I immediately get error over the image sequence location and Result information path boxes.  Web UI is showing the following:**

To create a public link, set `share=True` in `launch()`.
Creating model from config: F:\Stable Diffusion\webui\configs\v1-inference.yaml
Startup time: 13.8s (prepare environment: 4.4s, import torch: 3.2s, import gradio: 0.9s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.6s, setup codeformer: 0.1s, load scripts: 2.3s, create ui: 0.8s, gradio launch: 0.5s).
Applying attention optimization: xformers... done.
Model loaded in 6.4s (load weights from disk: 1.2s, create model: 0.4s, apply weights to model: 2.1s, apply dtype to VAE: 1.4s, load textual inversion embeddings: 0.1s, calculate empty prompt: 1.0s).
Uploaded video directory: C:\Users\Redacted\AppData\Local\Temp\gradio\49171a557a6b42d58c13fe113a7f915870c2d550\test.mp4
Traceback (most recent call last):
  File "F:\Stable Diffusion\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Stable Diffusion\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\Stable Diffusion\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\Stable Diffusion\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Stable Diffusion\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\Stable Diffusion\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\Stable Diffusion\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\Stable Diffusion\webui\extensions\next-view\scripts\next_view.py", line 69, in submit_video
    final_log = split_video_to_images(video, output_dir, final_log_textbox)
  File "F:\Stable Diffusion\webui\extensions\next-view\scripts\next_view.py", line 25, in split_video_to_images
    with subprocess.Popen(ffprobe_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True) as process:
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**I don't know what file it is looking for above. 

I have verified that "Add number to filename when saving" is not checked.  FFmpeg is installed and when I run cmd to verfiy I get:**

F:\>ffmpeg -version
ffmpeg version 2023-11-05-git-44a0148fad-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      58. 31.100 / 58. 31.100
libavcodec     60. 32.102 / 60. 32.102
libavformat    60. 17.100 / 60. 17.100
libavdevice    60.  4.100 / 60.  4.100
libavfilter     9. 13.100 /  9. 13.100
libswscale      7.  6.100 /  7.  6.100
libswresample   4. 13.100 /  4. 13.100
libpostproc    57.  4.100 / 57.  4.100

**Reactor runs fine on it's own.  No other extensions except for Adetailer, reactor, and next-view are running.  All extensions have been updated, I have also tried about 20 other video files with the same result.  I have also uninstalled and reinstalled Nextview.  Any suggestions would be appreciated.  Thanks**

**Comment by NextDiffusion** [comment]
The error you're encountering suggests that the script is unable to locate the "ffprobe.exe" executable. Are you sure you have that one included in the folder where your "ffmpeg.exe" is located?

**Comment by ibarelyknowwhatimdoing** [comment]
Yes it is in the same directory. Also in the directory is ffplay.exe

C:\>ffprobe -version
ffprobe version 2023-11-05-git-44a0148fad-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      58. 31.100 / 58. 31.100
libavcodec     60. 32.102 / 60. 32.102
libavformat    60. 17.100 / 60. 17.100
libavdevice    60.  4.100 / 60.  4.100
libavfilter     9. 13.100 /  9. 13.100
libswscale      7.  6.100 /  7.  6.100
libswresample   4. 13.100 /  4. 13.100
libpostproc    57.  4.100 / 57.  4.100

**Comment by ibarelyknowwhatimdoing** [comment]
Thanks for the hint.  I fixed the problem by copying the 3 ffmpeg files into the stable diffusion webui folder.

**Comment by NextDiffusion** [comment]
Perfect! Glad it works now :)
